#!/bin/bash

iquery --ignore-errors -anq "
remove(DBNSFP_V2p9_CHROMOSOME);
remove(DBNSFP_V2p9_VARIANT);

create array DBNSFP_V2p9_CHROMOSOME
< chromosome:string not null>
[ chromosome_id ];
store(build(DBNSFP_V2p9_CHROMOSOME, '[(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(X),(Y),(M)]', true), DBNSFP_V2p9_CHROMOSOME);

create array DBNSFP_V2p9_VARIANT
< ref                               :string null,
  alt                               :string null,
  aaref                             :string null,
  aaalt                             :string null,
  rs_dbSNP141                       :string null,
  hg18_pos                          :int64  null,
  hg38_chr                          :string null,
  hg38_pos                          :int64  null,
  genename                          :string null,
  Uniprot_acc                       :string null,
  Uniprot_id                        :string null,
  Uniprot_aapos                     :string null,
  Interpro_domain                   :string null,
  cds_strand                        :string null,
  refcodon                          :string null,
  SLR_test_statistic                :double null,
  codonpos                          :uint8 null,
  fold_degenerate                   :uint8 null,
  Ancestral_allele                  :string null,
  Ensembl_geneid                    :string null,
  Ensembl_transcriptid              :string null,
  aapos                             :string null,
  aapos_SIFT                        :string null,
  aapos_FATHMM                      :string null,
  SIFT_score                        :string null,
  SIFT_converted_rankscore          :double null,
  SIFT_pred                         :string null,
  Polyphen2_HDIV_score              :string null,
  Polyphen2_HDIV_rankscore          :double null,
  Polyphen2_HDIV_pred               :string null,
  Polyphen2_HVAR_score              :string null,
  Polyphen2_HVAR_rankscore          :double null,
  Polyphen2_HVAR_pred               :string null,
  LRT_score                         :double null,
  LRT_converted_rankscore           :double null,
  LRT_pred                          :string null,
  MutationTaster_score              :string null,
  MutationTaster_converted_rankscore:double null,
  MutationTaster_pred               :string null,
  MutationAssessor_score            :double null,
  MutationAssessor_rankscore        :double null,
  MutationAssessor_pred             :string null,
  FATHMM_score                      :double null,
  FATHMM_rankscore                  :double null,
  FATHMM_pred                       :string null,
  MetaSVM_score                     :double null,
  MetaSVM_rankscore                 :double null,
  MetaSVM_pred                      :string null,
  MetaLR_score                      :double null,
  MetaLR_rankscore                  :double null,
  MetaLR_pred                       :string null,
  Reliability_index                 :uint8 null,
  VEST3_score                       :double null,
  VEST3_rankscore                   :double null,
  PROVEAN_score                     :string null,
  PROVEAN_converted_rankscore       :double null,
  PROVEAN_pred                      :string null,
  CADD_raw                          :double null,
  CADD_raw_rankscore                :double null,
  CADD_phred                        :double null,
  GERPPP_NR                         :double null,
  GERPPP_RS                         :double null,
  GERPPP_RS_rankscore               :double null,
  phyloP46way_primate               :double null,  
  pyloP46way_primate_rankscore      :double null,     
  phyloP46way_placental             :double null, 
  phyloP46way_placental_rankscore   :double null,
  phyloP100way_vertebrate           :double null,  
  phyloP100way_vertebrate_rankscore :double null,
  phastCons46way_primate            :double null, 
  phastCons46way_primate_rankscore  :double null, 
  phastCons46way_placental          :double null, 
  phastCons46way_placental_rankscore:double null,
  phastCons100way_vertebrate        :double null, 
  phastCons100way_vertebrate_rankscore: double null,
  SiPhy_29way_pi                    :string null,
  SiPhy_29way_logOdds               :double null,
  SiPhy_29way_logOdds_rankscore     :double null,
  LRT_Omega                         :double null,
  UniSNP_ids                        :string null,
  KGp1_AC                           :int64 null,
  KGp1_AF                           :double null,
  KGp1_AFR_AC                       :int64 null,
  KGp1_AFR_AF                       :double null,
  KGp1_EUR_AC                       :int64 null,
  KGp1_EUR_AF                       :double null,
  KGp1_AMR_AC                       :int64 null,
  KGp1_AMR_AF                       :double null,
  KGp1_ASN_AC                       :int64 null,
  KGp1_ASN_AF                       :double null,
  ESP6500_AA_AF                     :double null,
  ESP6500_EA_AF                     :double null,
  ARIC5606_AA_AC                    :int64 null,
  ARIC5606_AA_AF                    :double null,
  ARIC5606_EA_AC                    :int64 null,
  ARIC5606_EA_AF                    :double null,
  ExAC_AC                           :int64 null,
  ExAC_AF                           :double null,
  ExAC_Adj_AC                       :int64 null,
  ExAC_Adj_AF                       :double null,
  ExAC_AFR_AC                       :int64 null,
  ExAC_AFR_AF                       :double null,
  ExAC_AMR_AC                       :int64 null,
  ExAC_AMR_AF                       :double null,
  ExAC_EAS_AC                       :int64 null,
  ExAC_EAS_AF                       :double null,
  ExAC_FIN_AC                       :int64 null,
  ExAC_FIN_AF                       :double null,
  ExAC_NFE_AC                       :int64 null,
  ExAC_NFE_AF                       :double null,
  null_SAS_AC                       :int64 null,
  ExAC_SAS_AF                       :double null,
  clinvar_rs                        :string null,
  clinvar_clnsig                    :int8 null,
  clinvar_trait                     :string null,
  COSMIC_ID                         :string null,
  COSMIC_CNT                        :int64 null
> 
[
 chromosome_id =0:*,1,0,
 pos           =0:*,10000000,0,
 variant_no    =0:19,20,0
];"
