#!/bin/bash

iquery --ignore-errors -anq "
remove(DBNSFP_CHROMOSOME);
remove(DBNSFP_VARIANT);

create array DBNSFP_CHROMOSOME
< chromosome:string not null>
[ chromosome_id ];
store(build(DBNSFP_CHROMOSOME, '[(1),(2),(3),(4),(5),(6),(7),(8),(9),(10),(11),(12),(13),(14),(15),(16),(17),(18),(19),(20),(21),(22),(X),(Y),(M)]', true), DBNSFP_CHROMOSOME);

create array DBNSFP_VARIANT
< ref                               :string null,
  alt                               :string null,
  aaref                             :string null,
  aaalt                             :string null,
  rs_dbSNP142                       :string null,
  hg19_chr                          :string null,
  hg19_pos                          :int64  null,
  hg18_chr                          :string null,
  hg18_pos                          :int64  null,
  genename                          :string null,
  cds_strand                        :string null,
  refcodon                          :string null,
  codonpos                          :uint8 null,
  codon_degeneracy                  :string null,
  Ancestral_allele                  :string null,
  AltaiNeandertal                   :string null,
  Denisova                          :string null,
  Ensembl_geneid                    :string null,
  Ensembl_transcriptid              :string null,
  Ensembl_proteinid                 :string null,
  aapos                             :string null,
  SIFT_score                        :string null,
  SIFT_converted_rankscore          :double null,
  SIFT_pred                         :string null,
  Uniprot_acc_Polyphen2             :string null,
  Uniprot_id_Polyphen2              :string null,
  Uniprot_aapos_Polyphen2           :string null,
  Polyphen2_HDIV_score              :string null,
  Polyphen2_HDIV_rankscore          :double null,
  Polyphen2_HDIV_pred               :string null,
  Polyphen2_HVAR_score              :string null,
  Polyphen2_HVAR_rankscore          :double null,
  Polyphen2_HVAR_pred               :string null,
  LRT_score                         :double null,
  LRT_converted_rankscore           :double null,
  LRT_pred                          :string null,
  LRT_Omega                         :double null,
  MutationTaster_score              :string null,
  MutationTaster_converted_rankscore:double null,
  MutationTaster_pred               :string null,
  MutationTaster_model              :string null,
  MutationTaster_AAE                :string null,
  Uniprot_id_MutationAssessor       :string null,
  Uniprot_variant_MutationAssessor  :string null,
  MutationAssessor_score            :double null,
  MutationAssessor_rankscore        :double null,
  MutationAssessor_pred             :string null,
  FATHMM_score                      :double null,
  FATHMM_converted_rankscore        :double null,
  FATHMM_pred                       :string null,
  PROVEAN_score                     :string null,
  PROVEAN_converted_rankscore       :double null,
  PROVEAN_pred                      :string null,
  MetaSVM_score                     :double null,
  MetaSVM_rankscore                 :double null,
  MetaSVM_pred                      :string null,
  MetaLR_score                      :double null,
  MetaLR_rankscore                  :double null,
  MetaLR_pred                       :string null,
  Reliability_index                 :uint8 null,
  GERPPP_NR                         :double null,
  GERPPP_RS                         :double null,
  GERPPP_RS_rankscore               :double null,
  phyloP7way_vertebrate             :double null,
  phyloP7way_vertebrate_rankscore   :double null,
  phastCons7way_vertebrate          :double null,
  phastCons7way_vertebrate_rankscore:double null,
  SiPhy_29way_pi                    :string null,
  SiPhy_29way_logOdds               :double null,
  SiPhy_29way_logOdds_rankscore     :double null,
  KGp3_AC                           :int64 null,
  KGp3_AF                           :double null,
  KGp3_AFR_AC                       :int64 null,
  KGp3_AFR_AF                       :double null,
  KGp3_EUR_AC                       :int64 null,
  KGp3_EUR_AF                       :double null,
  KGp3_AMR_AC                       :int64 null,
  KGp3_AMR_AF                       :double null,
  KGp3_EAS_AC                       :int64 null,
  KGp3_EAS_AF                       :double null,
  KGp3_SAS_AC                       :int64 null,
  KGp3_SAS_AF                       :double null,
  TWINSUK_AC                        :int64 null,
  TWINSUK_AF                        :double null,
  ALSPAC_AC                         :int64 null,
  ALSPAC_AF                         :double null,
  ESP6500_AA_AC                     :int64 null,
  ESP6500_AA_AF                     :double null,
  ESP6500_EA_AC                     :int64 null,
  ESP6500_EA_AF                     :double null,
  ExAC_AC                           :int64 null,
  ExAC_AF                           :double null,
  ExAC_Adj_AC                       :int64 null,
  ExAC_Adj_AF                       :double null,
  ExAC_AFR_AC                       :int64 null,
  ExAC_AFR_AF                       :double null,
  ExAC_AMR_AC                       :int64 null,
  ExAC_AMR_AF                       :double null,
  ExAC_EAS_AC                       :int64 null,
  ExAC_EAS_AF                       :double null,
  ExAC_FIN_AC                       :int64 null,
  ExAC_FIN_AF                       :double null,
  ExAC_NFE_AC                       :int64 null,
  ExAC_NFE_AF                       :double null,
  null_SAS_AC                       :int64 null,
  ExAC_SAS_AF                       :double null,
  clinvar_rs                        :string null,
  clinvar_clnsig                    :int8 null,
  clinvar_trait                     :string null,
  Interpro_domain                   :string null
> 
[
 chromosome_id =0:*,1,0,
 pos           =0:*,10000000,0,
 variant_no    =0:19,20,0
];"
